#!/usr/bin/env bash
# This script modifies /etc/hosts to change localhost and facebook.com IP mappings

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Remove existing entries for localhost and facebook.com (if any)
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add the required mappings
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
